[icons]
name = "none"

[icons.overrides]
memory_mem = " RAM "
bat_full = " FULL"
update = " ^ "

[theme]
name = "gruvbox-dark"

[theme.overrides]
separator = ""
idle_bg = "#3c3836"      # dark1
idle_fg = "#ebdbb2"      # light1
info_bg = "#076678"      # faded blue
info_fg = "#ebdbb2"      # light1
good_bg = "#79740e"      # faded green
good_fg = "#ebdbb2"      # light1

warning_bg = "#fabd2f"   # bright yellow
warning_fg = "#3c3836"   # dark1
critical_bg = "#fb4934"  # bright red
critical_fg = "#3c3836"  # dark1

[[block]]
block = "time"
interval = 30
format = "%R"

[[block]]
block = "time"
interval = 30
format = "%a %d %b"

#[[block]]
#block = "keyboard_layout"
#driver = "localebus"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug} GiB"
format_swap = "{SUg} GiB"
clickable = false

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "used"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "pacman"

[[block]]
block = "networkmanager"

[[block]]
block = "sound"
on_click = "pavucontrol"

[[block]]
block = "battery"
device = "BAT1"
format = "{percentage}%"
interval = 5
